from pathlib import Path
from rdkit import Chem
from rdkit.Chem import AllChem, Draw

def sanitize_smiles(smiles: str) -> str:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Invalid or ambiguous SMILES: {smiles}")
    return Chem.MolToSmiles(mol, canonical=True)


def smiles_to_xyz(smiles: str, xyz_path: Path, n_confs: int = 10) -> Path:
    """
    Generate 3D coordinates from a SMILES string using RDKit conformer generation.
    Performs multiple conformer generation and selects the lowest-energy one.
    Writes the lowest-energy conformer to an XYZ file.

    Args:
        smiles: canonical SMILES string
        xyz_path: Path to output XYZ file
        n_confs: number of conformers to generate

    Returns:
        Path to the generated XYZ file
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Invalid SMILES: {smiles}")
    mol = Chem.AddHs(mol)

    # Generate multiple conformers
    conf_ids = AllChem.EmbedMultipleConfs(mol, numConfs=n_confs, randomSeed=42)
    if not conf_ids:
        raise RuntimeError("Failed to generate 3D conformers.")

    energies = []
    for conf_id in conf_ids:
        try:
            AllChem.UFFOptimizeMolecule(mol, confId=conf_id)
            ff = AllChem.UFFGetMoleculeForceField(mol, confId=conf_id)
            energies.append(ff.CalcEnergy())
        except Exception:
            energies.append(float('inf'))

    # Select the lowest-energy conformer
    best_idx = conf_ids[energies.index(min(energies))]
    conf = mol.GetConformer(best_idx)

    # Write XYZ
    lines = [str(mol.GetNumAtoms()), "Generated by RDKit conformer search"]
    for atom in mol.GetAtoms():
        pos = conf.GetAtomPosition(atom.GetIdx())
        lines.append(f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")

    xyz_path.write_text("\n".join(lines))
    return xyz_path


def smiles_to_png(smiles: str, output_path: Path) -> Path:
    smiles = sanitize_smiles(smiles)
    mol = Chem.MolFromSmiles(smiles)
    AllChem.Compute2DCoords(mol)
    img = Draw.MolToImage(mol, size=(300, 300))
    img.save(output_path)
    return output_path

def xyz_to_png(xyz_path: Path, output_path: Path) -> Path:
    with xyz_path.open() as f:
        lines = f.readlines()[2:]
    mol = Chem.RWMol()
    for line in lines:
        parts = line.split()
        if len(parts) < 4:
            continue
        mol.AddAtom(Chem.Atom(parts[0]))
    AllChem.Compute2DCoords(mol)
    img = Draw.MolToImage(mol, size=(300, 300))
    img.save(output_path)
    return output_path
